name: Unofficial LV Docs CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install dependencies
      run: |
        npm ci
    - name: Build
      run: |
        npm run build
        npm pack
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: npmpackage
        path: ./unofficial-lvdocs-*.tgz

  deploy:
      needs: build
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-18.04
      steps:
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Setup pages deploy
        run: gem install dpl
      - name: Download GitHub Pages Output
        uses: actions/download-artifact@v2
        with:
          name: npmpackage
      - name: Extract GitHub Pages Output
        run: tar zxvf unofficial-lvdocs-*.tgz
      - name: Deploy to GitHub Pages
        run: dpl --verbose --provider=pages --repo=rajsite/unofficial-lvdocs --local_dir=package/dist --skip_cleanup --name=rajsite --email=rajsite@users.noreply.github.com --github-token=${{ secrets.GHPAGES_TOKEN }}
